export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A majestic dragon soaring through the night sky.",
  "An enchanted forest filled with glowing mushrooms and fairies.",
  "A futuristic cityscape with flying cars and neon lights.",
  "A serene beach sunset with palm trees and waves crashing.",
  "A steampunk-inspired world with mechanical animals and airships.",
  "A mystical underwater kingdom with mermaids and sea creatures.",
  "An alien landscape with strange rock formations and colorful flora.",
  "A cyberpunk city with towering skyscrapers and holographic billboards.",
  "An ancient temple hidden deep within the jungle.",
  "A time-traveling adventure through different historical eras.",
  "A celestial realm with floating islands and glowing stars.",
  "A magical library with endless shelves of mystical books.",
  "A surreal dreamscape with floating islands and waterfalls.",
  "A futuristic space station orbiting a distant planet.",
  "A lush tropical paradise with waterfalls and exotic wildlife.",
  "A mysterious portal leading to another dimension.",
  "A futuristic utopian city with advanced technology.",
  "A cosmic nebula with colorful swirls of gas and dust.",
  "A virtual reality world with surreal landscapes.",
  "A serene Japanese garden with cherry blossom trees.",
  "An underwater city with bioluminescent sea creatures.",
  "A fantastical floating island in the sky.",
  "A mesmerizing bioluminescent cave filled with glowing organisms.",
  "A futuristic cityscape during a rainstorm.",
  "A tranquil lakeside cabin surrounded by snowy mountains.",
  "A time-bending portal revealing scenes from different ages.",
  "A futuristic space colony on a distant moon.",
  "A futuristic high-tech laboratory with advanced equipment.",
  "An ancient wizard's tower in a mystical forest.",
  "A cosmic journey through the galaxy.",
  "A cyberpunk street scene with neon signs and flying drones.",
  "A magical marketplace with floating stalls and unique items.",
  "A dystopian cityscape with dark skies and towering skyscrapers.",
  "An enchanted castle perched on a cliff overlooking the sea.",
  "A surreal landscape with melting buildings and distorted shapes.",
  "A whimsical carnival with colorful rides and carnival games.",
  "An underwater research station exploring ocean depths.",
  "A serene mountain lake with reflections of surrounding peaks.",
  "A futuristic city with giant mushrooms as buildings.",
  "A mythical creature roaming through a mystical forest.",
  "An alien world with peculiar plant life and landscapes.",
  "A hidden cave with ancient runes and symbols on the walls.",
  "A futuristic train station with levitating trains.",
  "A floating island with waterfalls cascading into the abyss.",
  "A serene countryside landscape with rolling hills and grazing animals.",
  "A futuristic garden with levitating plants and flowers.",
  "An ancient ruins site with crumbling pillars and statues.",
  "A whimsical treehouse village high up in the canopy.",
  "A futuristic spaceship exploring uncharted territories.",
  "An otherworldly desert with colorful sand dunes and rock formations.",
];
